#define MICROPY_HW_BOARD_NAME "Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM"
#define MICROPY_HW_MCU_NAME "ESP32S3"
#define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "ESP32S3"

#define MICROPY_HW_I2C0_SCL (4)
#define MICROPY_HW_I2C0_SDA (3)

#define MICROPY_HW_SPI1_MOSI (35)
#define MICROPY_HW_SPI1_SCK (36)
#define MICROPY_HW_SPI1_MISO (37)